### ISSUE TITLE
HALT instruction (0x76) increments PC

### ISSUE THREAD

**Issue by friol** [raddad772/jsmoo#28] opened 2023-03-18 07:08 UTC
Almost all the HALT tests seem to expect PC incremented by one, while PC should remain unchanged, for the definition of HALT.

**Comment by raddad772** [comment] 2023-04-04 13:21
You're right! HALT is pretty problematic to test since it has no end. But you're right, PC shouldn't have incremented.

I have not fixed this behavior in my core, but have in the tests, I think. Please let me know if it is fixed for real.

**Comment by friol** [comment] 2023-04-16 17:13
I confirm that now it's fixed. Thanks.

**Comment by redcode** [comment] 2023-12-23 17:08
Sorry, but the `halt` instruction **does** increment PC during the opcode fetch, as all other instructions do. The CPU neither decrements nor avoids incrementing PC _"so that the instruction is re-executed"_ as Sean Young writes in section 5.4 of "The Undocumented Z80 Documented". After entering the HALT state, the CPU repeatedly executes an internal NOP operation. Each NOP consists of 1 M1 cycle of 4 T-states that fetches and disregards the next opcode after `halt` without incrementing PC. This opcode is read again and again until an exit condition occurs (i.e., INT, NMI or RESET).

This was first [documented](http://primrosebank.net/computers/z80/z80_special_reset.htm) by Tony Brewer in 2014, and was later re-confirmed by the [HALT2INT](https://github.com/redcode/Z80/wiki/HALT2INT) test written by Mark Woodmass (AKA Woody) in 2021.

**Comment by raddad772** [comment] 2024-02-22 14:39
@redcode recently merged in a fix that should have gotten this too, I'm pretty sure

**Closed as completed by raddad772** 2024-02-22 14:39 UTC
